### ISSUE TITLE
Bug in ResolvedRequestObject.OpenId4VPAuthorization.toSessionTranscript() - DirectPost response mode fails on ClassCastException

### ISSUE THREAD

**Issue by filip-hladky** [eu-digital-identity-wallet/eudi-lib-android-wallet-core#91]
Hi, 
in our testing during Hackathons and futher we are encountering bug if we want to use response mode "direct_post". 
It fails in Openid4vpManager on class cast to DirectPostJwt.

Expected behavior is either:
- DirectPost is listed as unsupported option and is not accepted
- or DirectPost is supported and request is properly processed by Wallet. 

> `       E  FATAL EXCEPTION: DefaultDispatcher-worker-9
                                                                                                    Process: eu.europa.ec.euidi, PID: 6657
                                                                                                    java.lang.ClassCastException: eu.europa.ec.eudi.openid4vp.ResponseMode$DirectPost cannot be cast to eu.europa.ec.eudi.openid4vp.ResponseMode$DirectPostJwt
                                                                                                    	at eu.europa.ec.eudi.wallet.transfer.openid4vp.OpenId4vpManager.toSessionTranscript(OpenId4vpManager.kt:383)
                                                                                                    	at eu.europa.ec.eudi.wallet.transfer.openid4vp.OpenId4vpManager.access$toSessionTranscript(OpenId4vpManager.kt:141)
                                                                                                    	at eu.europa.ec.eudi.wallet.transfer.openid4vp.OpenId4vpManager$resolveRequestUri$1.invokeSuspend(OpenId4vpManager.kt:216)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)`

**Comment by vkanellopoulos** [comment]
Hello @filip-hladky 

Thank you for reporting this issue and providing detailed feedback. This issue has been addressed and will be resolved in the next release. We appreciate your patience and understanding.
